### ISSUE TITLE
Review problem statement

### ISSUE THREAD

**Issue by smiths** [LeilaMousapour/Brain-Computer-Interface-#1]
@LeilaMousapour in the future, please create an issue for me to review your work.  This is a better way to manage all of the class projects than e-mail.  :smile:  

In the interest of time, I've created the issue for this case.  The problem statement is available at:

https://github.com/LeilaMousapour/Brain-Computer-Interface-/blob/master/docs/ProblemStatement/ProblemStatement.pdf

**Comment by smiths** [comment]
Good start @LeilaMousapour.  I have the following comments.

- Please review the writing checklist.  Specifically, please review the following points:
  - hard-wrap the LaTeX text at 80 characters (for diffs)
  - include the `.gitignore` file from the blank project template
- Please review the problem statement checklist.  Specifically:
  - The inputs are fairly clear, but what is the type of the outputs?  It looks like there is a multiplication symbol in the problem statement.  Are you returning a product, or is this a tuple, or something else?  Your description mentions spatial coordinates, but the Output summary doesn't suggest space to me.

You can also remove the sample comments, since we aren't using them right now.

Once you have made the above changes, we can close this issue and approve your problem statement.

**Comment by smiths** [comment]
@LeilaMousapour, have you made any progress toward addressing this issue?  It would be nice for us to close it, so that you can focus on your SRS.

**Comment by LeilaMousapour** [comment]
Hi Dr.Smith, Thank you for reviewing my problem statement.
I have applied all your comments. I hope this version is fine.

**Comment by smiths** [comment]
@LeilaMousapour, yes, the problem statement is improved.  Since the text still doesn't have hard-wraps, I added them for you, in commit 2404cae.

The type of the outputs still isn't clear to me.  Your document says:

"Number of sources x time samples (recording time/sampling frequency) μvolt (source time courses)"

For the types of these outputs, the simple guesses are as follows:

Number of sources: Natural number
time samples: Real number?
microvolt: Real number?

It looks like your output is a natural number multiplied by a real number, and then, I guess another real number?

Is that really what you mean?  Since you are calculating over space, I would think that the type of the output might be a multidimensional sequence?  Or maybe the output type would be a function that maps from Real x Real X Real to Real?

Your problem statement is approved.  We can work out your output details via your SRS.
