### ISSUE TITLE
TM, GD, DD, and IM are not cross referenced

### ISSUE THREAD

**Issue by shmouses** [LeilaMousapour/Brain-Computer-Interface-#10]
Hi @LeilaMousapour, 
TMs, GDs, DDs, and IMs are not linked to each other in the context. I don't know if this is a typo or the links don't really exist but if they are typos, you have "GD?" in your tables but I do not see any GDs in the submitted pdf. So if you have them somewhere and you have forgotten to add them be aware that they are not in your pdf.

**Comment by LeilaMousapour** [comment]
Fixed #c047177
