### ISSUE TITLE
Fix BibTeX for SRS

### ISSUE THREAD

**Issue by smiths** [LeilaMousapour/Brain-Computer-Interface-#16]
@LeilaMousapour, BibTeX isn't working on your SRS.  Based on the error message, it looks like your bib file is not under versions control.

```
I couldn't open database file SRS.bib
---line 119 of file SRS.aux
 : \bibdata{SRS
 :             }
I'm skipping whatever remains of this command
I found no database files---while reading file SRS.aux
Warning--I didn't find a database entry for "michel_eeg_2019"
Warning--I didn't find a database entry for "Parnas1978"
Warning--I didn't find a database entry for "SmithAndLai2005"
```

**Comment by LeilaMousapour** [comment]
Dr. Smith, I uploaded it again, could you please check if it works now?

**Comment by smiths** [comment]
Yes, it works now.  :smile:  

It isn't a priority, but you might want to clean up your bib files.  You have an SRS.bib file in the docs folder and in the SRS folder.  In the original blank project template there is a refs folder where the References.bib file is located.  The advantage of the approach in the blank project template is that the same References.bib file can be used for all of the documents.  :smile:
