### ISSUE TITLE
VnV ready for review

### ISSUE THREAD

**Issue by LeilaMousapour** [LeilaMousapour/Brain-Computer-Interface-#17]
Dear Dr. Smith and reviews, 
I would appreciate it if you could review my VnV plan.
@smiths @gabrielasd @muralidn

**Comment by smiths** [comment]
@LeilaMousapour, please create separate issues for each reviewer.

**Comment by smiths** [comment]
Spelling error corrected in 923fc6c.

**Comment by smiths** [comment]
Feedback on VnV Plan is given in e93c89b.

**Comment by LeilaMousapour** [comment]
Dear Dr. Smith @smiths 
Thank you very much for the comments on my VnV plan.
I tried by best to addressed almost all the issues you pointed out in addition to fixing the reviewers comments.
 #7197df8
