### ISSUE TITLE
VnV - Output for test-input test case

### ISSUE THREAD

**Issue by muralidn** [LeilaMousapour/Brain-Computer-Interface-#21]
@LeilaMousapour 

The output for this case is not recorded,

![image](https://user-images.githubusercontent.com/71282513/101092562-dd32b880-35df-11eb-9546-44381f61f03d.png)

**Comment by LeilaMousapour** [comment]
Hi Naveen @muralidn 
I actually have mentioned that the output is an "error message".
Thank you!

**Comment by muralidn** [comment]
I see it now. Sorry my bad.
