### ISSUE TITLE
VnV- Quantifying error

### ISSUE THREAD

**Issue by muralidn** [LeilaMousapour/Brain-Computer-Interface-#22]
@LeilaMousapour 

For the tests involving comparing data with the Brainstorm software, how are the error (differences, if any) between the outputs quantified? 

Apologies if this question does not make any sense in the context of your project :).

**Comment by LeilaMousapour** [comment]
Hi Naveen @muralidn ,

It is a good question. I have to calculate the norm difference between the signal output of the brainstorm software and mine and report a relative error. 

fixed in #7197df8 
Thank you
