### ISSUE TITLE
VnV - The use of "We"

### ISSUE THREAD

**Issue by muralidn** [LeilaMousapour/Brain-Computer-Interface-#24]
@LeilaMousapour 

The word "we" is used throughout the document. It may be helpful for the reader if it was clarified. That is if we refer to the development team or verification team?

**Comment by LeilaMousapour** [comment]
Hi Naveen @muralidn 
Thank you for reviewing my VnV plan.
By "we" I meant the developer and wherever I wanted to address the reviewers, I explicitly mentioned them.
You are right though; I should not use active grammar in technical writing.
