### ISSUE TITLE
VnV - Minor typos

### ISSUE THREAD

**Issue by gabrielasd** [LeilaMousapour/Brain-Computer-Interface-#25]
Hi @LeilaMousapour 
Your System VnV plan looks good to me :) and I don't have much to add to what the other reviewers have already pointed out.

I noticed two typos, one in Table 1 from section 5.3, the other in the "How test will be performed" section of the test-SimulatedEEG:
![typo2](https://user-images.githubusercontent.com/26312264/101125608-a2bd2180-35c7-11eb-9433-2996f70c2319.png)

![typo](https://user-images.githubusercontent.com/26312264/101125625-af417a00-35c7-11eb-871e-e89f8e6c4d7d.png)

**Comment by LeilaMousapour** [comment]
Fixed in  #7197df8
