### ISSUE TITLE
VnV - Incomplete sentence

### ISSUE THREAD

**Issue by gabrielasd** [LeilaMousapour/Brain-Computer-Interface-#26]
There is a sentence in sections 4.2 and 4.3 of the System VnV plan that doesn't look complete to me:
![incomplete_idea](https://user-images.githubusercontent.com/26312264/101125753-fc255080-35c7-11eb-9de0-d6d685b42005.png)

**Comment by LeilaMousapour** [comment]
Fixed in #7197df8
