### ISSUE TITLE
VnV - Measurement of accuracy

### ISSUE THREAD

**Issue by gabrielasd** [LeilaMousapour/Brain-Computer-Interface-#28]
Hi Leila, 
I have a question related to the non-functional requirement NR1, maybe it isn't applicable to your project but I thought I would ask anyway. 
You say in section 5.2 "The accuracy for the computed solution should meet the level of accuracy achieved by other commercial softwares..."
Do you have or know of any specific value to measure this accuracy? If so maybe it could be mentioned in section 5.2 or 4.5...?

**Comment by LeilaMousapour** [comment]
Hi Gaby @gabrielasd 
Thank you very much for all your comments.
This was a very important point. I clarified the in  #7197df8.
