### ISSUE TITLE
Cross references didn't generate correctly

### ISSUE THREAD

**Issue by gabrielasd** [LeilaMousapour/Brain-Computer-Interface-#3]
Hi @LeilaMousapour,
Through the SRS document (starting on page 8 with the Theoretical models) the cross-references to the IM, GD, DD and A didn't generate correctly.
Here are two examples of how it looks now:
![Screenshot from 2020-10-25 21-07-35](https://user-images.githubusercontent.com/26312264/97124796-e63e8900-1707-11eb-9257-a612053634ac.png)

![Screenshot from 2020-10-25 21-06-59](https://user-images.githubusercontent.com/26312264/97124823-0b32fc00-1708-11eb-8234-229e0b129303.png)

**Comment by LeilaMousapour** [comment]
Fixed #c047177
