### ISSUE TITLE
Possible typo on Input Variables table of SRS

### ISSUE THREAD

**Issue by gabrielasd** [LeilaMousapour/Brain-Computer-Interface-#4]
Hello,
Is the abbreviation EGG on Table 1 page 15 (Input Variables) a typo of EEG or is it an actual abbreviation of something?
![Screenshot from 2020-10-25 21-11-59](https://user-images.githubusercontent.com/26312264/97124967-9f9d5e80-1708-11eb-996b-d39d5236c867.png)

**Comment by LeilaMousapour** [comment]
Fixed in #ae1648a
