### ISSUE TITLE
References to T, GD, IM, DD in Assumptions section of SRS

### ISSUE THREAD

**Issue by gabrielasd** [LeilaMousapour/Brain-Computer-Interface-#5]
Hello @LeilaMousapour,
The introductory paragraph of the Assumptions section (page 7 in the SRS) seems to indicate that a cross-reference to pertinent theoretical models, general definitions, etc, is going to be made next to each listed assumption, but they don't appear. You could maybe remove that sentence,
![Screenshot from 2020-10-25 21-01-55](https://user-images.githubusercontent.com/26312264/97125464-682fb180-170a-11eb-94f4-532d40d334db.png)
 or add the references?

**Comment by smiths** [comment]
@gabrielasd thank you for the issue.  @LeilaMousapour, of the two options given, you should choose adding the cross references to the parts of the document that depend on the assumptions.  It isn't fun to do, but this traceability is invaluable in the event that one of the assumptions changes.

When you close this issue, please include in your comment the commit hash where the changes are made.

**Comment by LeilaMousapour** [comment]
Thanks for the issue @gabrielasd .
Fixed in #ae1648a .
